# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  format:libpapilo:
    desc: Format only libpapilo codes
    cmds:
      - clang-format --version
      - clang-format -i src/libpapilo.* test/libpapilo/*.{cpp,c}

  build:all:
    cmds:
      - cmake --preset debug
      - cmake --build --preset debug

  test:all:
    cmds:
      - task: build:all
      - ctest --preset debug

  test:libpapilo:
    cmds:
      - cmake --build --preset debug --target libpapilo_unit_test
      - ctest --preset debug --tests-regex libpapilo

  local-install:
    desc: Build and install to local_install directory
    cmds:
      - cmake --preset local-install
      - cmake --build --preset local-install
      - cmake --install build/local-install

  package:tgz:
    desc: Create TGZ archive for macOS distribution
    cmds:
      - cmake --preset default
      - cmake --build --preset default
      - cpack --preset tgz
