name: "Setup Test Environment"
description: "Setup common environment for testing jobs"

runs:
  using: "composite"
  steps:
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ github.token }}

    - name: Cache APT packages
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: cmake ninja-build libtbb-dev libboost-dev
        version: 1.0
