name: "Setup Test Environment"
description: "Setup common environment for testing jobs"

runs:
  using: "composite"
  steps:
    - name: Setup sccache with GitHub Actions cache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ github.token }}

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: >-
          cmake ninja-build libtbb-dev file
          libboost-dev libboost-iostreams-dev libboost-program-options-dev libboost-serialization-dev
        version: 1.0

    - name: Install dependencies (macOS)
      shell: bash
      if: runner.os == 'macOS'
      run: |
        brew install cmake ninja boost tbb
