name: Package libpapilo

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*-jij.*"
  workflow_dispatch:

jobs:
  build:
    name: Build and Package libpapilo
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: Linux
          - os: macos-latest
            platform: Darwin
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libboost-all-dev libtbb-dev build-essential

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake ninja boost tbb

      - name: Configure CMake
        run: cmake --preset default

      - name: Build libpapilo
        run: cmake --build --preset default --target libpapilo

      - name: Create package
        run: cpack --preset tgz

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpapilo-package-${{ matrix.platform }}
          path: build/packages/*.tar.gz
          retention-days: 30

  publish:
    name: Publish to GitHub Release
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages

      - name: Create GitHub Release with generated packages
        uses: softprops/action-gh-release@v2
        with:
          files: packages/**/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
