name: Package

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: Linux
          - os: macos-latest
            platform: Darwin
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-test-environment

      - name: Configure CMake
        run: cmake --preset default

      - name: Build libpapilo
        run: cmake --build --preset default --target libpapilo

      - name: Create TGZ package
        run: cpack --preset tgz

      - name: Create DEB package (Linux only)
        if: runner.os == 'Linux'
        run: cpack --preset deb

      - name: Upload TGZ package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: libpapilo-package-${{ matrix.platform }}
          path: build/packages/*.tar.gz
          retention-days: 30

      - name: Upload DEB package as artifact (Linux only)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: libpapilo-deb-package
          path: build/packages/*.deb
          retention-days: 30

  test-deb:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install tools for testing DEB package
        run: |
          apt-get update
          apt-get install -y file gcc

      - name: Download DEB package
        uses: actions/download-artifact@v4
        with:
          name: libpapilo-deb-package
          path: .

      - name: Install dependencies and test DEB package
        run: |
          apt-get update
          apt-get install -y file gcc
          
          # List the DEB file
          ls -la *.deb
          
          # Show package information
          dpkg -I *.deb
          
          # Try to install the package using dpkg first (to see exact error)
          dpkg -i *.deb || echo "dpkg install failed, checking dependencies"
          
          # If dpkg failed, try to fix dependencies
          apt-get -f install -y || echo "apt-get -f install failed"
          
          # Alternative approach: install dependencies manually then force install
          if [ ! -f /usr/lib/libpapilo.so ]; then
            echo "Trying manual dependency resolution..."
            # Force install ignoring dependencies for testing
            dpkg -i --force-depends *.deb
          fi
          
          # Verify the library is installed
          ls -la /usr/lib/libpapilo.so* || echo "Library files not found"
          ls -la /usr/include/libpapilo.h || echo "Header file not found"
          
          # Test that the library can be loaded
          ldd /usr/lib/libpapilo.so || echo "ldd failed"
          
          # Compile and run the link test
          if [ -f /usr/lib/libpapilo.so ] && [ -f /usr/include/libpapilo.h ]; then
            gcc -o linktest test/libpapilo/LinkTest.c -lpapilo && ./linktest
          else
            echo "Skipping link test due to missing files"
          fi

  publish:
    permissions:
      contents: write
    if: github.event_name == 'release'
    needs: [build, test-deb]
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages

      - name: Add packages to GitHub Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: |
            packages/**/*.tar.gz
            packages/**/*.deb
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
